import './globals.css'
import type { Metadata } from 'next'
import  { Providers } from '@/app/components/theme/provider'
import Dock from './components/dock/Dock'
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
// import Navbar from './components/navbar'
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
        <body className="antialiased max-w-2xl mb-40 flex flex-col md:flex-row mx-4 mt-8 lg:mx-auto">
        <Providers>
          <main className="flex-auto min-w-0 mt-6 flex flex-col px-2 md:px-0">
          {/* <Navbar /> */}
            {children}
          </main>
          <Dock />
        </Providers>
       </body>
    </html>
  )
}
